### PR TITLE
add switchout to be used with "eval"

### PR DESCRIPTION
**Pull request by jotix16**

### CODE REVIEW

**Comment by albertz** [comment]
Why is this in `asr`?

**Comment by jotix16** [comment]
Was unsure about the place to put it so I put it near `specaugment`. Should it go to `training/`?

**Comment by albertz** [comment]
> Was unsure about the place to put it so I put it near `specaugment`. Should it go to `training/`?

Well, this is not related at all to `asr`, so definitely not `asr`.
Yes, maybe `training`. I don't have a better idea now.

**Comment by jotix16** [comment]
can I still do changes to this or a new pr is required?

**Comment by albertz** [comment]
> can I still do changes to this or a new pr is required?

No, once it is merged, please make a new PR.

**Pull request merged**
